/usr/bin/ipython*
/usr/bin/irunner
/usr/bin/pycolor
/usr/lib/python2.*
/usr/share/doc/ipython/examples/core
/usr/share/doc/ipython/examples/lib
/usr/share/doc/ipython/examples/parallel
/usr/share/doc/ipython/extensions
docs/emacs/ipython.el		usr/share/emacs/site-lisp
docs/examples/core/ipython.desktop usr/share/applications/
/usr/bin/ipcluster
/usr/bin/ipcontroller
/usr/bin/ipengine
/usr/bin/iplogger
docs/examples/core/ipython-qtconsole.desktop usr/share/applications/
